@startuml
skinparam packageStyle rectangle
skinparam classAttributeIconSize 0

package "Engine Core Systems (Global Functions)" {

    rectangle "Mesh System" {
        class "Mesh.h" << (F, #FF7700) >> {
            + LoadMesh(vertices, stride) : MeshID
            + LoadMeshIndexed(vertices, stride, indices) : MeshID
            + GetMesh(id) : Mesh*
            + ShutdownMeshes()

        }
    }

    rectangle "Renderer System" {
        class "Renderer.h" << (F, #FF7700) >> {
            + InitRenderer()
            + ClearScreen()
            + RenderEntity(Entity, Camera)
            + SwapBuffers()
            + WireFrame(bool)
            +WindowIsOpen(): bool
            +CloseWindow()
        }
    }

    rectangle "Input System" {
        class "Input.h" << (F, #FF7700) >> {
            + InitInput(window)
            + IsKeyPressed(key) : bool
            + GetMouseDelta(dx, dy)
        }
    }
}
'================== ASSET MANAGER ==============

package "AssetManager"{

   
    class EntityManager {
        EntityManager()
        ~EntityManager()

        EntityID CreateEntity(const std::string& name);
        void DestroyEntity(EntityID id);
        void DestroyEntity(const std::string& name);
        void DestroyAllEntities();
        Engine::Entity* GetEntity(const std::string& name);
        Engine::Entity* GetEntity(EntityID id);
        
        std::vector<Engine::Entity*> GetAllEntities();

        EntityID nextID;
       //two data Structures for good performance
        std::vector<std::unique_ptr<Engine::Entity>> entities;
        std::unordered_map<std::string, EntityID> name_to_id;
        std::unordered_map<EntityID, size_t> id_to_index;
    

    }

     class ShaderManager {


        ShaderID nextID
        std::unordered_map<ShaderID, std::unique_ptr<Engine::IShader>> map
        std::unordered_map<std::string,ShaderID> name_to_id
        std::unordered_map<ShaderID,std::string> id_to_name
        std::vector<ShaderID> shaderRemoveMemory
        bool allDestroyed
        Engine::IShader* GetShader(ShaderID id)
        Engine::IShader* GetShader(const std::string& name)
        void DestroyShader(ShaderID id)
        void DestroyShader(const std::string& name)
        Engine::IShader* CreateShader(std::string name,const std::string& pathVertex, const std::string& pathFrag)
        void DestroyAllShaders()
        void cleanUp()
    }

}

package "Logging and Profiling"{

       enum  LogLevel{
        ERROR
        WARNING
        INFO
        DEBUG
        SUCCESS
inline std::string logLevelToString(LogLevel level)
    }
   

    interface ILogger{
      
    virtual ~ILogger()

    virtual void Log(const std::string& msg,LogLevel loggerType)

}
class ConsoleLogger  {}
class UILogger{}
class FileLogger{}

class ScopeTimer
class FrameTimer

}

'================ Editor =====================
package "Editor"{


class Editor {


        Math::Vec3 selectedEntityColor


        Editor(World::Map& map)
        void selectObject(Engine::Camera* camera)
        void unselectObject()
        void drawEntities(Engine::Camera& camera)
        void update(float dt, Engine::Camera& camera)
        Engine::Entity* selectedEntity = nullptr
        World::Map& map;
        Engine::Shader EditorShader

        Gizmos gizmos
        Engine::Camera* selectedCamera = nullptr

}

class Gizmos{
  Gizmos()
   ~Gizmos() 

        void drawGizmos(Engine::Entity& entity, Engine::Camera& camera)

        void manipulateEntity(Engine::Entity &entity)
}

}


' ================= ENGINE =================
package "Engine" {



 

            class MeshSystem <<Subsystem>> {
                - meshes
                - nextMeshID
                + LoadMesh()
                + LoadMeshIndexed()
                + GetMesh()
                + ShutdownMeshes()
            }
rectangle "Shaders"{

            Interface IShader {
                  virtual ~IShader() = default;

        virtual void use() const = 0;

       

        // Uniforms
        virtual void setMat4(const std::string& name, const Math::Mat4& mat) const= 0;
        virtual void setVec3(const std::string& name, const Math::Vec3& vec3) const= 0;
        virtual void setFloat(const std::string& name, float v) const= 0;
        virtual void setBool(const std::string& name, bool v) const= 0;

            }
            
     class OpenGLShader  {

         unsigned int ID;

         OpenGLShader(const char* vertexPath,
                      const char* fragmentPath) ;

         ~OpenGLShader() override;

         void use() const override;

         void setMat4(const std::string& name,
                      const Math::Mat4& mat) const override;

         void setVec3(const std::string& name,
                      const Math::Vec3& vec3) const override;

         void setFloat(const std::string& name,
                       float v) const override;

         void setBool(const std::string& name,
                      bool v) const override;

    
     }
 }




    rectangle "Any Object in World has"{


           class Mesh <<struct>> {
               - VAO : unsigned int = 0
               - VBO : unsigned int = 0
               - EBO : unsigned int = 0
               - vertexCount : uint32_t = 0
               - indexCount : int = 0
               - indexed : bool = false
               -getLocalAABB();
           }





    class Transform <<struct>> {
        - position : Vec3
        - rotation : Vec3
        - scale : Vec3
        + GetModelMatrix() : Mat4
    }

    class Material <<struct>> {
        - shader : Shader*
        - color : Vec3
    }

    class Entity <<struct>> {
        - meshID : int
        - transform : Transform
        - material : Material
        -Geometry::AABB GetAABB() const;
    }
}
    class Camera{
        position : Vec3
        up :Vec3
        front :Vec3
        aspect ratio : float
        fov : radian
        near Plane : float
        far Plane : float

        +Camera(Vec3& pos, Vec3& target,Vec3& upVector)
        +GetViewMatrix() : Mat4 4x4
        +GetPrespectiveMatrix(): Mat4 4x4
        + Move(Vec3& delta);
        +Rotate(float pitchRadians, float yawRadians);
    }
    class CameraController{
        speed: float
        yaw: float
        pitch: float
        MousesSensitivity: float
        +Update(Camera& camera, float deltaTime,MoveMode mode)
        +setSpeed(float speed)
       enum MoveMode {Flying, Player}

       CameraController --> MoveMode : uses
    }


    class Input {
        +InitInput()
        +IsKeyPressed(key)
        +GetMouseDelta(dx, dy)
    }

    class Physics {
        TODO
      
    }


}

' ================= WORLD ==================
package "World" {

    class Map {
    TODO
       
    }
}

' ================= GAME ===================
package "Game TODO" {

    class Player {
       TODO
    }

    class Enemy {
     NEEDED? TODO
    }
}

' ================= RELATIONS ==============
@enduml