@startuml
skinparam packageStyle rectangle
skinparam classAttributeIconSize 0

' ================= ENGINE =================
package "Engine" {

    class Camera{
        position : Vec3
        up :Vec3
        front :Vec3
        aspect ratio : float
        fov : radian
        near Plane : float
        far Plane : float

        +Camera(Vec3& pos, Vec3& target,Vec3& upVector)
        +GetViewMatrix() : Mat4 4x4
        +GetPrespectiveMatrix(): Mat4 4x4
        + Move(Vec3& delta);
        +Rotate(float pitchRadians, float yawRadians);
    }


    class Input {
        +InitInput()
        +IsKeyPressed(key)
        +GetMouseDelta(dx, dy)
    }

    class Physics {
        TODO
        +InitPhysics()
        +UpdatePhysics(dt)
    }

    class Renderer {
        +InitRenderer()
        +ClearScreen()
        +RenderMesh(meshID, x, y, z)//to Remove
        +RenderEntity(Entity, Camera)
        +SwapBuffers()
    }
}

' ================= WORLD ==================
package "World" {

    class Map {
    TODO
        +LoadMap(path)
        +UpdateMap(dt)
        +RenderMap()
        +IsSolid(x, y, z)
    }
}

' ================= GAME ===================
package "Game TODO" {

    class Player {
        x : float
        y : float
        z : float
        health : int
        meshID : int

        +InitPlayer()
        +UpdatePlayer(dt)
        +RenderPlayer()
        +TakeDamage(amount)
        +FireWeapon()
        +ReloadWeapon()
    }

    class Enemy {
        x : float
        y : float
        z : float
        health : int
        meshID : int

        +InitEnemy()
        +UpdateEnemy(dt)
        +RenderEnemy()
        +TakeDamage(amount)
        +FireWeapon()
    }
}

' ================= RELATIONS ==============
Player --> Input     : reads
Player --> Physics   : uses
Player --> Renderer  : renders
Player --> Map       : collision

Enemy --> Physics    : uses
Enemy --> Renderer   : renders
Enemy --> Map        : collision

Map --> Renderer : renders

@enduml
