@startuml
namespace Window {

interface IWindow {
    +isOpen(): bool
    +close(): void
    +getSize(width: int, height: int): void
    +pollEvents(): void
    +swapBuffers(): void
    +setBackgroundColor(r: float, g: float, b: float, a: float): void
    +getNativeHandle(): void*
}

class GLFWWindow {
    -window: GLFWwindow*
    -lastTime: float
    +GLFWWindow(width: int, height: int, title: string)
    +~GLFWWindow()
    +isOpen(): bool
    +close(): void
    +getSize(width: int, height: int): void
    +pollEvents(): void
    +swapBuffers(): void
    +setBackgroundColor(r: float, g: float, b: float, a: float): void
    +setFramebufferSizeCallback(cb: GLFWframebuffersizefun): void
    +getNativeHandle(): void*
    +getDeltaTime(): float
}

 ' -------------------------
    ' Beziehungen
    ' -------------------------

IWindow <|.. GLFWWindow
}

@enduml